/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : AnnouncementId,
  'title' : string,
  'active' : boolean,
  'announcementType' : AnnouncementType,
  'icon' : [] | [string],
  'createdAt' : Timestamp,
  'color' : [] | [string],
  'message' : string,
}
export type AnnouncementId = bigint;
export type AnnouncementType = { 'warning' : null } |
  { 'other' : null } |
  { 'info' : null } |
  { 'error' : null };
export interface Application {
  'id' : ApplicationId,
  'status' : ApplicationStatus,
  'applicantId' : UserId,
  'responses' : Array<string>,
  'submittedAt' : Timestamp,
  'feedback' : [] | [string],
  'applicantDiscordId' : DiscordId,
  'positionId' : PositionId,
  'internalNotes' : [] | [string],
}
export type ApplicationId = bigint;
export type ApplicationStatus = { 'pendingReview' : null } |
  { 'underReview' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type BlacklistScope = { 'full' : null } |
  { 'department' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface Department {
  'id' : DepartmentId,
  'name' : string,
  'description' : string,
}
export type DepartmentId = bigint;
export type DiscordId = string;
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface Position {
  'id' : PositionId,
  'title' : string,
  'open' : boolean,
  'description' : string,
  'positionType' : PositionType,
  'requirements' : Array<string>,
  'departmentId' : DepartmentId,
}
export type PositionId = bigint;
export type PositionType = { 'contract' : null } |
  { 'paid' : null } |
  { 'unpaid' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Role = { 'applicant' : null } |
  { 'dprtLead' : null } |
  { 'admin' : null } |
  { 'reviewer' : null } |
  { 'blacklisted' : null } |
  { 'dprtReviewer' : null } |
  { 'dprtBlacklisted' : null };
export interface Session {
  'expiresAt' : Timestamp,
  'username' : string,
  'userId' : UserId,
  'discordId' : DiscordId,
}
export interface Settings {
  'guildRequired' : boolean,
  'clientId' : string,
  'guildId' : string,
  'clientSecret' : string,
  'botToken' : string,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface User {
  'id' : UserId,
  'departments' : Array<DepartmentId>,
  'username' : string,
  'role' : Role,
  'discordId' : DiscordId,
}
export type UserId = Principal;
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  'addStaffMember' : ActorMethod<
    [DiscordId, string, Role, Array<DepartmentId>],
    User
  >,
  'blacklistApplicant' : ActorMethod<
    [ApplicationId, BlacklistScope, string],
    undefined
  >,
  'changePermission' : ActorMethod<[UserId, Role, Array<DepartmentId>], User>,
  'createDepartment' : ActorMethod<[string, string], Department>,
  'createPosition' : ActorMethod<
    [string, string, Array<string>, PositionType, DepartmentId],
    Position
  >,
  'deactivateAnnouncement' : ActorMethod<[AnnouncementId], undefined>,
  'deleteDepartment' : ActorMethod<[DepartmentId], undefined>,
  'discordLoginComplete' : ActorMethod<[string], Session>,
  'discordLoginStart' : ActorMethod<[], string>,
  'execute' : ActorMethod<[string], Result>,
  'getApplication' : ActorMethod<[ApplicationId], [] | [Application]>,
  'getCallerPermission' : ActorMethod<[], [] | [User]>,
  'getCurrentUser' : ActorMethod<[], [] | [Session]>,
  'getDepartment' : ActorMethod<[DepartmentId], [] | [Department]>,
  'getPosition' : ActorMethod<[PositionId], [] | [Position]>,
  'getSettings' : ActorMethod<[], Settings>,
  'listAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'listApplications' : ActorMethod<[], Array<Application>>,
  'listApplicationsForReview' : ActorMethod<[], Array<Application>>,
  'listDepartments' : ActorMethod<[], Array<Department>>,
  'listPositions' : ActorMethod<[], Array<Position>>,
  'listStaff' : ActorMethod<[], Array<User>>,
  'logout' : ActorMethod<[], undefined>,
  'openApplicationForReview' : ActorMethod<[ApplicationId], Application>,
  'postAnnouncement' : ActorMethod<
    [string, string, AnnouncementType, [] | [string], [] | [string]],
    Announcement
  >,
  'schema' : ActorMethod<[], string>,
  'sendBotDm' : ActorMethod<[DiscordId, string], undefined>,
  'setApplicationStatus' : ActorMethod<
    [ApplicationId, ApplicationStatus, [] | [string], [] | [string]],
    Application
  >,
  'setGuildId' : ActorMethod<[string], undefined>,
  'setGuildRequired' : ActorMethod<[boolean], undefined>,
  'setPositionOpen' : ActorMethod<[PositionId, boolean], Position>,
  'submitApplication' : ActorMethod<[PositionId, Array<string>], Application>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateDepartment' : ActorMethod<[DepartmentId, string, string], Department>,
  'updatePosition' : ActorMethod<
    [PositionId, string, string, Array<string>, PositionType, DepartmentId],
    Position
  >,
  'updateSettings' : ActorMethod<[Settings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];