/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DiscordId = IDL.Text;
export const Role = IDL.Variant({
  'applicant' : IDL.Null,
  'dprtLead' : IDL.Null,
  'admin' : IDL.Null,
  'reviewer' : IDL.Null,
  'blacklisted' : IDL.Null,
  'dprtReviewer' : IDL.Null,
  'dprtBlacklisted' : IDL.Null,
});
export const DepartmentId = IDL.Nat;
export const UserId = IDL.Principal;
export const User = IDL.Record({
  'id' : UserId,
  'departments' : IDL.Vec(DepartmentId),
  'username' : IDL.Text,
  'role' : Role,
  'discordId' : DiscordId,
});
export const ApplicationId = IDL.Nat;
export const BlacklistScope = IDL.Variant({
  'full' : IDL.Null,
  'department' : IDL.Null,
});
export const Department = IDL.Record({
  'id' : DepartmentId,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const PositionType = IDL.Variant({
  'contract' : IDL.Null,
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const PositionId = IDL.Nat;
export const Position = IDL.Record({
  'id' : PositionId,
  'title' : IDL.Text,
  'open' : IDL.Bool,
  'description' : IDL.Text,
  'positionType' : PositionType,
  'requirements' : IDL.Vec(IDL.Text),
  'departmentId' : DepartmentId,
});
export const AnnouncementId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Session = IDL.Record({
  'expiresAt' : Timestamp,
  'username' : IDL.Text,
  'userId' : UserId,
  'discordId' : DiscordId,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ApplicationStatus = IDL.Variant({
  'pendingReview' : IDL.Null,
  'underReview' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Application = IDL.Record({
  'id' : ApplicationId,
  'status' : ApplicationStatus,
  'applicantId' : UserId,
  'responses' : IDL.Vec(IDL.Text),
  'submittedAt' : Timestamp,
  'feedback' : IDL.Opt(IDL.Text),
  'applicantDiscordId' : DiscordId,
  'positionId' : PositionId,
  'internalNotes' : IDL.Opt(IDL.Text),
});
export const Settings = IDL.Record({
  'guildRequired' : IDL.Bool,
  'clientId' : IDL.Text,
  'guildId' : IDL.Text,
  'clientSecret' : IDL.Text,
  'botToken' : IDL.Text,
});
export const AnnouncementType = IDL.Variant({
  'warning' : IDL.Null,
  'other' : IDL.Null,
  'info' : IDL.Null,
  'error' : IDL.Null,
});
export const Announcement = IDL.Record({
  'id' : AnnouncementId,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'announcementType' : AnnouncementType,
  'icon' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'color' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  'addStaffMember' : IDL.Func(
      [DiscordId, IDL.Text, Role, IDL.Vec(DepartmentId)],
      [User],
      [],
    ),
  'blacklistApplicant' : IDL.Func(
      [ApplicationId, BlacklistScope, IDL.Text],
      [],
      [],
    ),
  'changePermission' : IDL.Func(
      [UserId, Role, IDL.Vec(DepartmentId)],
      [User],
      [],
    ),
  'createDepartment' : IDL.Func([IDL.Text, IDL.Text], [Department], []),
  'createPosition' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), PositionType, DepartmentId],
      [Position],
      [],
    ),
  'deactivateAnnouncement' : IDL.Func([AnnouncementId], [], []),
  'deleteDepartment' : IDL.Func([DepartmentId], [], []),
  'discordLoginComplete' : IDL.Func([IDL.Text], [Session], []),
  'discordLoginStart' : IDL.Func([], [IDL.Text], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApplication' : IDL.Func(
      [ApplicationId],
      [IDL.Opt(Application)],
      ['query'],
    ),
  'getCallerPermission' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getCurrentUser' : IDL.Func([], [IDL.Opt(Session)], ['query']),
  'getDepartment' : IDL.Func([DepartmentId], [IDL.Opt(Department)], ['query']),
  'getPosition' : IDL.Func([PositionId], [IDL.Opt(Position)], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'listAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'listApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'listApplicationsForReview' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'listDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
  'listPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
  'listStaff' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'logout' : IDL.Func([], [], []),
  'openApplicationForReview' : IDL.Func([ApplicationId], [Application], []),
  'postAnnouncement' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        AnnouncementType,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Announcement],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sendBotDm' : IDL.Func([DiscordId, IDL.Text], [], []),
  'setApplicationStatus' : IDL.Func(
      [ApplicationId, ApplicationStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [Application],
      [],
    ),
  'setGuildId' : IDL.Func([IDL.Text], [], []),
  'setGuildRequired' : IDL.Func([IDL.Bool], [], []),
  'setPositionOpen' : IDL.Func([PositionId, IDL.Bool], [Position], []),
  'submitApplication' : IDL.Func(
      [PositionId, IDL.Vec(IDL.Text)],
      [Application],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateDepartment' : IDL.Func(
      [DepartmentId, IDL.Text, IDL.Text],
      [Department],
      [],
    ),
  'updatePosition' : IDL.Func(
      [
        PositionId,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        PositionType,
        DepartmentId,
      ],
      [Position],
      [],
    ),
  'updateSettings' : IDL.Func([Settings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DiscordId = IDL.Text;
  const Role = IDL.Variant({
    'applicant' : IDL.Null,
    'dprtLead' : IDL.Null,
    'admin' : IDL.Null,
    'reviewer' : IDL.Null,
    'blacklisted' : IDL.Null,
    'dprtReviewer' : IDL.Null,
    'dprtBlacklisted' : IDL.Null,
  });
  const DepartmentId = IDL.Nat;
  const UserId = IDL.Principal;
  const User = IDL.Record({
    'id' : UserId,
    'departments' : IDL.Vec(DepartmentId),
    'username' : IDL.Text,
    'role' : Role,
    'discordId' : DiscordId,
  });
  const ApplicationId = IDL.Nat;
  const BlacklistScope = IDL.Variant({
    'full' : IDL.Null,
    'department' : IDL.Null,
  });
  const Department = IDL.Record({
    'id' : DepartmentId,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const PositionType = IDL.Variant({
    'contract' : IDL.Null,
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
  });
  const PositionId = IDL.Nat;
  const Position = IDL.Record({
    'id' : PositionId,
    'title' : IDL.Text,
    'open' : IDL.Bool,
    'description' : IDL.Text,
    'positionType' : PositionType,
    'requirements' : IDL.Vec(IDL.Text),
    'departmentId' : DepartmentId,
  });
  const AnnouncementId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Session = IDL.Record({
    'expiresAt' : Timestamp,
    'username' : IDL.Text,
    'userId' : UserId,
    'discordId' : DiscordId,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ApplicationStatus = IDL.Variant({
    'pendingReview' : IDL.Null,
    'underReview' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Application = IDL.Record({
    'id' : ApplicationId,
    'status' : ApplicationStatus,
    'applicantId' : UserId,
    'responses' : IDL.Vec(IDL.Text),
    'submittedAt' : Timestamp,
    'feedback' : IDL.Opt(IDL.Text),
    'applicantDiscordId' : DiscordId,
    'positionId' : PositionId,
    'internalNotes' : IDL.Opt(IDL.Text),
  });
  const Settings = IDL.Record({
    'guildRequired' : IDL.Bool,
    'clientId' : IDL.Text,
    'guildId' : IDL.Text,
    'clientSecret' : IDL.Text,
    'botToken' : IDL.Text,
  });
  const AnnouncementType = IDL.Variant({
    'warning' : IDL.Null,
    'other' : IDL.Null,
    'info' : IDL.Null,
    'error' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'id' : AnnouncementId,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'announcementType' : AnnouncementType,
    'icon' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'color' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    'addStaffMember' : IDL.Func(
        [DiscordId, IDL.Text, Role, IDL.Vec(DepartmentId)],
        [User],
        [],
      ),
    'blacklistApplicant' : IDL.Func(
        [ApplicationId, BlacklistScope, IDL.Text],
        [],
        [],
      ),
    'changePermission' : IDL.Func(
        [UserId, Role, IDL.Vec(DepartmentId)],
        [User],
        [],
      ),
    'createDepartment' : IDL.Func([IDL.Text, IDL.Text], [Department], []),
    'createPosition' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), PositionType, DepartmentId],
        [Position],
        [],
      ),
    'deactivateAnnouncement' : IDL.Func([AnnouncementId], [], []),
    'deleteDepartment' : IDL.Func([DepartmentId], [], []),
    'discordLoginComplete' : IDL.Func([IDL.Text], [Session], []),
    'discordLoginStart' : IDL.Func([], [IDL.Text], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApplication' : IDL.Func(
        [ApplicationId],
        [IDL.Opt(Application)],
        ['query'],
      ),
    'getCallerPermission' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getCurrentUser' : IDL.Func([], [IDL.Opt(Session)], ['query']),
    'getDepartment' : IDL.Func(
        [DepartmentId],
        [IDL.Opt(Department)],
        ['query'],
      ),
    'getPosition' : IDL.Func([PositionId], [IDL.Opt(Position)], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'listAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'listApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'listApplicationsForReview' : IDL.Func(
        [],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'listDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
    'listPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
    'listStaff' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'logout' : IDL.Func([], [], []),
    'openApplicationForReview' : IDL.Func([ApplicationId], [Application], []),
    'postAnnouncement' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          AnnouncementType,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Announcement],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sendBotDm' : IDL.Func([DiscordId, IDL.Text], [], []),
    'setApplicationStatus' : IDL.Func(
        [
          ApplicationId,
          ApplicationStatus,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Application],
        [],
      ),
    'setGuildId' : IDL.Func([IDL.Text], [], []),
    'setGuildRequired' : IDL.Func([IDL.Bool], [], []),
    'setPositionOpen' : IDL.Func([PositionId, IDL.Bool], [Position], []),
    'submitApplication' : IDL.Func(
        [PositionId, IDL.Vec(IDL.Text)],
        [Application],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateDepartment' : IDL.Func(
        [DepartmentId, IDL.Text, IDL.Text],
        [Department],
        [],
      ),
    'updatePosition' : IDL.Func(
        [
          PositionId,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          PositionType,
          DepartmentId,
        ],
        [Position],
        [],
      ),
    'updateSettings' : IDL.Func([Settings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };