/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type DiscordId = string;
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export type PositionId = bigint;
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface User {
    id: UserId;
    departments: Array<DepartmentId>;
    username: string;
    role: Role;
    discordId: DiscordId;
}
export interface Application {
    id: ApplicationId;
    status: ApplicationStatus;
    applicantId: UserId;
    responses: Array<string>;
    submittedAt: Timestamp;
    feedback?: string;
    applicantDiscordId: DiscordId;
    positionId: PositionId;
    internalNotes?: string;
}
export type DepartmentId = bigint;
export interface HttpHeader {
    value: string;
    name: string;
}
export type UserId = Principal;
export interface Settings {
    guildRequired: boolean;
    clientId: string;
    guildId: string;
    clientSecret: string;
    botToken: string;
}
export interface Session {
    expiresAt: Timestamp;
    username: string;
    userId: UserId;
    discordId: DiscordId;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface Position {
    id: PositionId;
    title: string;
    open: boolean;
    description: string;
    positionType: PositionType;
    requirements: Array<string>;
    departmentId: DepartmentId;
}
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface Department {
    id: DepartmentId;
    name: string;
    description: string;
}
export interface Cell {
    value: Value;
    name: string;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export type ApplicationId = bigint;
export type AnnouncementId = bigint;
export interface Announcement {
    id: AnnouncementId;
    title: string;
    active: boolean;
    announcementType: AnnouncementType;
    icon?: string;
    createdAt: Timestamp;
    color?: string;
    message: string;
}
export enum AnnouncementType {
    warning = "warning",
    other = "other",
    info = "info",
    error = "error"
}
export enum ApplicationStatus {
    pendingReview = "pendingReview",
    underReview = "underReview",
    rejected = "rejected",
    accepted = "accepted"
}
export enum BlacklistScope {
    full = "full",
    department = "department"
}
export enum PositionType {
    contract = "contract",
    paid = "paid",
    unpaid = "unpaid"
}
export enum Role {
    applicant = "applicant",
    dprtLead = "dprtLead",
    admin = "admin",
    reviewer = "reviewer",
    blacklisted = "blacklisted",
    dprtReviewer = "dprtReviewer",
    dprtBlacklisted = "dprtBlacklisted"
}
export interface backendInterface {
    addStaffMember(discordId: DiscordId, username: string, role: Role, departments: Array<DepartmentId>): Promise<User>;
    blacklistApplicant(applicationId: ApplicationId, scope: BlacklistScope, reason: string): Promise<void>;
    changePermission(userId: UserId, role: Role, departments: Array<DepartmentId>): Promise<User>;
    createDepartment(name: string, description: string): Promise<Department>;
    createPosition(title: string, description: string, requirements: Array<string>, positionType: PositionType, departmentId: DepartmentId): Promise<Position>;
    deactivateAnnouncement(id: AnnouncementId): Promise<void>;
    deleteDepartment(id: DepartmentId): Promise<void>;
    discordLoginComplete(code: string): Promise<Session>;
    discordLoginStart(): Promise<string>;
    execute(qJson: string): Promise<Result>;
    getApplication(id: ApplicationId): Promise<Application | null>;
    getCallerPermission(): Promise<User | null>;
    getCurrentUser(): Promise<Session | null>;
    getDepartment(id: DepartmentId): Promise<Department | null>;
    getPosition(id: PositionId): Promise<Position | null>;
    getSettings(): Promise<Settings>;
    listAnnouncements(): Promise<Array<Announcement>>;
    listApplications(): Promise<Array<Application>>;
    listApplicationsForReview(): Promise<Array<Application>>;
    listDepartments(): Promise<Array<Department>>;
    listPositions(): Promise<Array<Position>>;
    listStaff(): Promise<Array<User>>;
    logout(): Promise<void>;
    openApplicationForReview(id: ApplicationId): Promise<Application>;
    postAnnouncement(title: string, message: string, announcementType: AnnouncementType, color: string | null, icon: string | null): Promise<Announcement>;
    schema(): Promise<string>;
    sendBotDm(discordId: DiscordId, message: string): Promise<void>;
    setApplicationStatus(id: ApplicationId, status: ApplicationStatus, feedback: string | null, internalNotes: string | null): Promise<Application>;
    setGuildId(guildId: string): Promise<void>;
    setGuildRequired(required: boolean): Promise<void>;
    setPositionOpen(id: PositionId, open: boolean): Promise<Position>;
    submitApplication(positionId: PositionId, responses: Array<string>): Promise<Application>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateDepartment(id: DepartmentId, name: string, description: string): Promise<Department>;
    updatePosition(id: PositionId, title: string, description: string, requirements: Array<string>, positionType: PositionType, departmentId: DepartmentId): Promise<Position>;
    updateSettings(newSettings: Settings): Promise<void>;
}
import type { Announcement as _Announcement, AnnouncementId as _AnnouncementId, AnnouncementType as _AnnouncementType, Application as _Application, ApplicationId as _ApplicationId, ApplicationStatus as _ApplicationStatus, BlacklistScope as _BlacklistScope, Cell as _Cell, Department as _Department, DepartmentId as _DepartmentId, DiscordId as _DiscordId, Position as _Position, PositionId as _PositionId, PositionType as _PositionType, Result as _Result, Role as _Role, Session as _Session, Timestamp as _Timestamp, User as _User, UserId as _UserId, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addStaffMember(arg0: DiscordId, arg1: string, arg2: Role, arg3: Array<DepartmentId>): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.addStaffMember(arg0, arg1, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_User_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStaffMember(arg0, arg1, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_User_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async blacklistApplicant(arg0: ApplicationId, arg1: BlacklistScope, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blacklistApplicant(arg0, to_candid_BlacklistScope_n7(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blacklistApplicant(arg0, to_candid_BlacklistScope_n7(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async changePermission(arg0: UserId, arg1: Role, arg2: Array<DepartmentId>): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.changePermission(arg0, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_User_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePermission(arg0, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_User_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDepartment(arg0: string, arg1: string): Promise<Department> {
        if (this.processError) {
            try {
                const result = await this.actor.createDepartment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDepartment(arg0, arg1);
            return result;
        }
    }
    async createPosition(arg0: string, arg1: string, arg2: Array<string>, arg3: PositionType, arg4: DepartmentId): Promise<Position> {
        if (this.processError) {
            try {
                const result = await this.actor.createPosition(arg0, arg1, arg2, to_candid_PositionType_n9(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Position_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPosition(arg0, arg1, arg2, to_candid_PositionType_n9(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Position_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivateAnnouncement(arg0: AnnouncementId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateAnnouncement(arg0);
            return result;
        }
    }
    async deleteDepartment(arg0: DepartmentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDepartment(arg0);
            return result;
        }
    }
    async discordLoginComplete(arg0: string): Promise<Session> {
        if (this.processError) {
            try {
                const result = await this.actor.discordLoginComplete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.discordLoginComplete(arg0);
            return result;
        }
    }
    async discordLoginStart(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.discordLoginStart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.discordLoginStart();
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplication(arg0: ApplicationId): Promise<Application | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplication(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplication(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPermission(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPermission();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPermission();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUser(): Promise<Session | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUser();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUser();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDepartment(arg0: DepartmentId): Promise<Department | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepartment(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepartment(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPosition(arg0: PositionId): Promise<Position | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPosition(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPosition(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async listAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnnouncements();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnnouncements();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApplications(): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApplications();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApplications();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApplicationsForReview(): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApplicationsForReview();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApplicationsForReview();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDepartments(): Promise<Array<Department>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDepartments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDepartments();
            return result;
        }
    }
    async listPositions(): Promise<Array<Position>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPositions();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPositions();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStaff(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStaff();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStaff();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout();
            return result;
        }
    }
    async openApplicationForReview(arg0: ApplicationId): Promise<Application> {
        if (this.processError) {
            try {
                const result = await this.actor.openApplicationForReview(arg0);
                return from_candid_Application_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.openApplicationForReview(arg0);
            return from_candid_Application_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async postAnnouncement(arg0: string, arg1: string, arg2: AnnouncementType, arg3: string | null, arg4: string | null): Promise<Announcement> {
        if (this.processError) {
            try {
                const result = await this.actor.postAnnouncement(arg0, arg1, to_candid_AnnouncementType_n41(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Announcement_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postAnnouncement(arg0, arg1, to_candid_AnnouncementType_n41(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Announcement_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async sendBotDm(arg0: DiscordId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendBotDm(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendBotDm(arg0, arg1);
            return result;
        }
    }
    async setApplicationStatus(arg0: ApplicationId, arg1: ApplicationStatus, arg2: string | null, arg3: string | null): Promise<Application> {
        if (this.processError) {
            try {
                const result = await this.actor.setApplicationStatus(arg0, to_candid_ApplicationStatus_n44(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Application_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApplicationStatus(arg0, to_candid_ApplicationStatus_n44(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Application_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async setGuildId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGuildId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGuildId(arg0);
            return result;
        }
    }
    async setGuildRequired(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGuildRequired(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGuildRequired(arg0);
            return result;
        }
    }
    async setPositionOpen(arg0: PositionId, arg1: boolean): Promise<Position> {
        if (this.processError) {
            try {
                const result = await this.actor.setPositionOpen(arg0, arg1);
                return from_candid_Position_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPositionOpen(arg0, arg1);
            return from_candid_Position_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitApplication(arg0: PositionId, arg1: Array<string>): Promise<Application> {
        if (this.processError) {
            try {
                const result = await this.actor.submitApplication(arg0, arg1);
                return from_candid_Application_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitApplication(arg0, arg1);
            return from_candid_Application_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateDepartment(arg0: DepartmentId, arg1: string, arg2: string): Promise<Department> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDepartment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDepartment(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePosition(arg0: PositionId, arg1: string, arg2: string, arg3: Array<string>, arg4: PositionType, arg5: DepartmentId): Promise<Position> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePosition(arg0, arg1, arg2, arg3, to_candid_PositionType_n9(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_Position_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePosition(arg0, arg1, arg2, arg3, to_candid_PositionType_n9(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_Position_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
}
function from_candid_AnnouncementType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnnouncementType): AnnouncementType {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Announcement_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Announcement): Announcement {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Application_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Application {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PositionType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PositionType): PositionType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Position_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Position): Position {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_User_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Application]): Application | null {
    return value.length === 0 ? null : from_candid_Application_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Session]): Session | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Department]): Department | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Position]): Position | null {
    return value.length === 0 ? null : from_candid_Position_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PositionId;
    title: string;
    open: boolean;
    description: string;
    positionType: _PositionType;
    requirements: Array<string>;
    departmentId: _DepartmentId;
}): {
    id: PositionId;
    title: string;
    open: boolean;
    description: string;
    positionType: PositionType;
    requirements: Array<string>;
    departmentId: DepartmentId;
} {
    return {
        id: value.id,
        title: value.title,
        open: value.open,
        description: value.description,
        positionType: from_candid_PositionType_n13(_uploadFile, _downloadFile, value.positionType),
        requirements: value.requirements,
        departmentId: value.departmentId
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n17(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n21(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ApplicationId;
    status: _ApplicationStatus;
    applicantId: _UserId;
    responses: Array<string>;
    submittedAt: _Timestamp;
    feedback: [] | [string];
    applicantDiscordId: _DiscordId;
    positionId: _PositionId;
    internalNotes: [] | [string];
}): {
    id: ApplicationId;
    status: ApplicationStatus;
    applicantId: UserId;
    responses: Array<string>;
    submittedAt: Timestamp;
    feedback?: string;
    applicantDiscordId: DiscordId;
    positionId: PositionId;
    internalNotes?: string;
} {
    return {
        id: value.id,
        status: from_candid_ApplicationStatus_n26(_uploadFile, _downloadFile, value.status),
        applicantId: value.applicantId,
        responses: value.responses,
        submittedAt: value.submittedAt,
        feedback: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.feedback)),
        applicantDiscordId: value.applicantDiscordId,
        positionId: value.positionId,
        internalNotes: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.internalNotes))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AnnouncementId;
    title: string;
    active: boolean;
    announcementType: _AnnouncementType;
    icon: [] | [string];
    createdAt: _Timestamp;
    color: [] | [string];
    message: string;
}): {
    id: AnnouncementId;
    title: string;
    active: boolean;
    announcementType: AnnouncementType;
    icon?: string;
    createdAt: Timestamp;
    color?: string;
    message: string;
} {
    return {
        id: value.id,
        title: value.title,
        active: value.active,
        announcementType: from_candid_AnnouncementType_n36(_uploadFile, _downloadFile, value.announcementType),
        icon: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.icon)),
        createdAt: value.createdAt,
        color: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.color)),
        message: value.message
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    departments: Array<_DepartmentId>;
    username: string;
    role: _Role;
    discordId: _DiscordId;
}): {
    id: UserId;
    departments: Array<DepartmentId>;
    username: string;
    role: Role;
    discordId: DiscordId;
} {
    return {
        id: value.id,
        departments: value.departments,
        username: value.username,
        role: from_candid_Role_n5(_uploadFile, _downloadFile, value.role),
        discordId: value.discordId
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contract: null;
} | {
    paid: null;
} | {
    unpaid: null;
}): PositionType {
    return "contract" in value ? PositionType.contract : "paid" in value ? PositionType.paid : "unpaid" in value ? PositionType.unpaid : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingReview: null;
} | {
    underReview: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): ApplicationStatus {
    return "pendingReview" in value ? ApplicationStatus.pendingReview : "underReview" in value ? ApplicationStatus.underReview : "rejected" in value ? ApplicationStatus.rejected : "accepted" in value ? ApplicationStatus.accepted : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    other: null;
} | {
    info: null;
} | {
    error: null;
}): AnnouncementType {
    return "warning" in value ? AnnouncementType.warning : "other" in value ? AnnouncementType.other : "info" in value ? AnnouncementType.info : "error" in value ? AnnouncementType.error : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    applicant: null;
} | {
    dprtLead: null;
} | {
    admin: null;
} | {
    reviewer: null;
} | {
    blacklisted: null;
} | {
    dprtReviewer: null;
} | {
    dprtBlacklisted: null;
}): Role {
    return "applicant" in value ? Role.applicant : "dprtLead" in value ? Role.dprtLead : "admin" in value ? Role.admin : "reviewer" in value ? Role.reviewer : "blacklisted" in value ? Role.blacklisted : "dprtReviewer" in value ? Role.dprtReviewer : "dprtBlacklisted" in value ? Role.dprtBlacklisted : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Announcement>): Array<Announcement> {
    return value.map((x)=>from_candid_Announcement_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Application>): Array<Application> {
    return value.map((x)=>from_candid_Application_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Position>): Array<Position> {
    return value.map((x)=>from_candid_Position_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n3(_uploadFile, _downloadFile, x));
}
function to_candid_AnnouncementType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementType): _AnnouncementType {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_ApplicationStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_BlacklistScope_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlacklistScope): _BlacklistScope {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_PositionType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PositionType): _PositionType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PositionType): {
    contract: null;
} | {
    paid: null;
} | {
    unpaid: null;
} {
    return value == PositionType.contract ? {
        contract: null
    } : value == PositionType.paid ? {
        paid: null
    } : value == PositionType.unpaid ? {
        unpaid: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    applicant: null;
} | {
    dprtLead: null;
} | {
    admin: null;
} | {
    reviewer: null;
} | {
    blacklisted: null;
} | {
    dprtReviewer: null;
} | {
    dprtBlacklisted: null;
} {
    return value == Role.applicant ? {
        applicant: null
    } : value == Role.dprtLead ? {
        dprtLead: null
    } : value == Role.admin ? {
        admin: null
    } : value == Role.reviewer ? {
        reviewer: null
    } : value == Role.blacklisted ? {
        blacklisted: null
    } : value == Role.dprtReviewer ? {
        dprtReviewer: null
    } : value == Role.dprtBlacklisted ? {
        dprtBlacklisted: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementType): {
    warning: null;
} | {
    other: null;
} | {
    info: null;
} | {
    error: null;
} {
    return value == AnnouncementType.warning ? {
        warning: null
    } : value == AnnouncementType.other ? {
        other: null
    } : value == AnnouncementType.info ? {
        info: null
    } : value == AnnouncementType.error ? {
        error: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): {
    pendingReview: null;
} | {
    underReview: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == ApplicationStatus.pendingReview ? {
        pendingReview: null
    } : value == ApplicationStatus.underReview ? {
        underReview: null
    } : value == ApplicationStatus.rejected ? {
        rejected: null
    } : value == ApplicationStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlacklistScope): {
    full: null;
} | {
    department: null;
} {
    return value == BlacklistScope.full ? {
        full: null
    } : value == BlacklistScope.department ? {
        department: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
